### ISSUE TITLE
running behind nginx proxy

### ISSUE THREAD

**Issue by zeigerpuppy** [loomio/loomio#1834]
I have successfully installed loomio on Debian Wheezy (I can post a wiki of the process if it's useful to other users).
However, before I expose my server, I'd like to run it behind nginx (to have it SSL protected and more managable).

Is there a snippit of an nginx config to proxy loomio available?

**Comment by robguthrie** [comment]
nope. not readily at hand, but it would be the same as for any rails app.

**Comment by zeigerpuppy** [comment]
I'm a little inexperienced with ruby and there's quite a lot of different methods I've found by searching.
I tried just running loomio with "rails s"
which responds correctly at localhost:3000. 

Then I created the nginx config (below)
The site then responds to external queries but 
throws the following error in the browser:
```       
  def load_group
    @group ||= if group_subdomain_present? and group_id.blank?
               Group.published.find_by_subdomain!(subdomain)
             else
               Group.published.find_by_key!(group_id)
             end
```
It looks like it's trying to respond to the new domain query but this is not in the database?
I'm not sure how I should fix this or if this method is completely wrong.

here's the selected console log:
```
Started GET "/" for 128.0.0.94 at 2015-01-12 19:53:45 +1100
Processing by GroupsController#show as HTML
PG::UndefinedTable: ERROR:  relation "groups" does not exist
LINE 5:                WHERE a.attrelid = '"groups"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"groups"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

Completed 500 Internal Server Error in 42ms
** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false

ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "groups" does not exist
LINE 5:                WHERE a.attrelid = '"groups"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"groups"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
  app/controllers/group_base_controller.rb:42:in `load_group'
```
The nginx config:
```
server {
    listen 80;
    server_name loomio.myserver.net;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name loomio.myserver.net;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    root /opt/loomio/public/;

    location /images/(.+)(\?.*)? {
        root /opt/loomio/public/images/$1;
        internal;
    }

    location / {
        proxy_read_timeout 120;
        proxy_connect_timeout 120;

        proxy_redirect          off;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Sendfile-Type X-Accell-Redirect;

        if (-f $request_filename) {
            expires max;
            break;
        }

        if (!-f $request_filename) {
            proxy_pass http://127.0.0.1:3000;
            break;
        }
    }

    ssl on;
    ssl_certificate /etc/ssl/nginx/myserver.net_enc_chained.crt;
    ssl_certificate_key /etc/ssl/nginx/private/myserver.net_dec.key;

    ssl_session_timeout 5m;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
    ssl_prefer_server_ciphers on;
}
```

**Comment by gdpelican** [comment]
Have a gander through our [setting up a dev environment](https://github.com/loomio/loomio/wiki/Setup-a-Loomio-development-environment) wiki; my guess is something in the [Setup your database](https://github.com/loomio/loomio/wiki/Setup-a-Loomio-development-environment#setup-your-database) section didn't happen. :fish:

**Comment by zeigerpuppy** [comment]
Setting up the dev environment went well, and there were no database errors when accessing localhost:3000,
below are the actual steps I followed.

I think what is happening is that loomio treats a request to loomio.myserver.net differently
to localhost.  Not sure why


```
loomio
---------

https://github.com/loomio/loomio/wiki/Setup-a-Loomio-development-environment

aptitude install postgresql-client build-essential libssl-dev libpq-dev libmagickwand-dev nodejs imagemagick
sudo apt-get install nodejs -t unstable

apt-get install postgresql postgresql-contrib

git clone https://github.com/loomio/loomio /opt/loomio


adduser loomio
usermod --home /opt/loomio loomio
rm -r /home/loomio

sudo chown -R loomio:loomio /opt/loomio/
su loomio
cd ~
git remote add loomio git@github.com:loomio/loomio.git

git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc

test: type rbenv
#=> "rbenv is a function"

git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

	When a new version of ruby is released, you can update ruby-build with
	$ cd ~/.rbenv/plugins/ruby-build
	$ git pull

rbenv install 2.2.0
rbenv global 2.2.0

gem install bundler
rbenv rehash
bundle install

set up local db
---------------
su postgres

psql
		CREATE USER loomio WITH PASSWORD 'o..';	
		CREATE DATABASE loomio_development;
		CREATE DATABASE loomio_test;
		GRANT ALL PRIVILEGES ON DATABASE loomio_development to loomio;
		GRANT ALL PRIVILEGES ON DATABASE loomio_test to loomio;
		\q

psql loomio_development
		create extension hstore;		
		\q
psql loomio_test
		create extension hstore;
		\q

config/database.yml
		development:
		  adapter: postgresql
		  database: loomio
		  username: loomio
		  password: ****

		test:
		  adapter: postgresql
		  database: loomio_test
		  username: loomio
		  password: ****


Start loomio:
	rails s


test:
	lynx localhost:3000
Works	
```

**Comment by gdpelican** [comment]
Hm, I could be wrong, but I still don't see a call to `rake db:setup` in there, which would mean that none of the migrations have been run.

It's very possible that everything on the landing page (what you'd hit when you go to localhost:3000 while logged out) is static content, which wouldn't require a database call.

**Comment by zeigerpuppy** [comment]
ah, yes you are right, thanks, I had run that before but then reset my database!
looking better now!

**Comment by zeigerpuppy** [comment]
a simpler nginx config is looking a bit better,
it's mostly working now but the links to access groups are directing to the wrong sub-domain
e.g.:
https://myserver.net/g/ne4VLYrK/test2
instead of https://loomio.myserver.net/g/ne4VLYrK/test2

if I enter the subdomain correctly manually it works. feels like 90% of the way there!

```
server {
    listen 80;
    server_name loomio.myserver.net;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name loomio.myserver.net;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    # loomio
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_$
        proxy_pass http://127.0.0.1:3000;
        proxy_redirect off;
    }

    ssl on;
    ssl_certificate /etc/ssl/nginx/myserver.net_enc_chained.crt;
    ssl_certificate_key /etc/ssl/nginx/private/myserver.net_dec.key;

    ssl_session_timeout 5m;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
    ssl_prefer_server_ciphers on;
}

**Comment by yourcelf** [comment]
It's generally [not recommended](https://stackoverflow.com/questions/10859671/webrick-as-production-server-vs-thin-or-unicorn) to use the ``rails server`` webrick development server in a production environment.  Most rails deployments use [passenger](https://www.digitalocean.com/community/tutorials/how-to-install-rails-and-nginx-with-passenger-on-ubuntu) -- you could probably start at step 5 in that tutorial.

**Comment by zeigerpuppy** [comment]
Thanks @yourcelf, that guide looks good, seems a much more sane way to run things!
I'll post a wiki describing the Debian install once I get it all running properly.
