### ISSUE TITLE
Emojis used in place of Unicode characters yield 404 from maxcdn

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6658]
Unicode characters (`↓` in this case) are being replaced by emojis, but the links are broken:

![image](https://user-images.githubusercontent.com/195073/84897700-2a86a080-b0fa-11ea-8c77-1ccbd584a53c.png)

The image URL is `https://twemoji.maxcdn.com/v/latest/72x72/2193.png`, which is a 404…

**Comment by robguthrie** [comment]
can you send me a link to where this is happening?

**Comment by robguthrie** [comment]
Ooooooo gosh.

The text stored and sent to browsers is unicode, but we replace unicode for imgs on browsers that dont support native unicode emojis. In other words, this is emoji fallback code for linux and windows.

That's likely to be you, eh?

Seems like those emojis have been removed from their CDN.

Thanks for reporting. Should be fixed now.

**Comment by madduck** [comment]
I can still see it trying to use an image on Linux on an existing post. Will this only be fixed for new posts?

I am quite sure my setup supported Unicode before emojis were even invented. How is it determined when to fall back to emoji images?

**Comment by robguthrie** [comment]
Hi @madduck. 

Would you mind checking this again for me? I had to rollback for another issue when you checked last time.

Fallback operates by rendering a unicode emoji to a 2d canvas element and testing for the correct pixel colour. If that fails unicode emojis are rendered as imgs by the frontend.

**Comment by madduck** [comment]
@robguthrie I'm still seeing it, but it's the same post, I have not made a new post. But I understand this is at render-time, so it should work for old threads too if fixed, right?

**Comment by robguthrie** [comment]
that's right. The data is stored as unicode. I'll turn fallback off for now and see how it goes.

**Comment by robguthrie** [comment]
I've tested this with windows 7 and can confirm emoji fallback support is working fine now. It was just an issue with MaxCDN.

**Comment by madduck** [comment]
On https://www.loomio.org/d/GUREjNPW/frequently-asked-questions/2, I can still see a broken image, which is pointing to the URL https://www.loomio.org/img/emojis/2193.png

**Comment by robguthrie** [comment]
oh, ok, that image is missing from the set. I'll switch to Openmoji.

**Comment by robguthrie** [comment]
hrrrmm, actually neither of these icon sets have an image for unicode 2193. I've removed that range from our regex. pushing up a new version now, it'll leave those chars alone.

**Comment by robguthrie** [comment]
if you have the inclination, please test again by refreshing after 11:15am

**Comment by madduck** [comment]
Now fixed.

**Comment by robguthrie** [comment]
super

**Comment by madduck** [comment]
This is back @robguthrie, e.g. `https://www.loomio.org/img/emojis/27ac.png` (the arrow in my nickname) is a 404.

**Comment by robguthrie** [comment]
this is fixed/totally irrelevant now.
